### ISSUE TITLE
Bug: When switching groups, the player disappears 

### ISSUE THREAD

**Issue by sloukit** [sloukit/pydew-valley-uzh#227]
#### Bug Description
If you switch groups (click 'yes' when asked if you want to leave the ingroup and join the outgroup), the player disappears.

#### Expected Behavior
The player should be visible, with a gradually changing appearance: First he loses all his items (hat, necklace), then he gets the same colour as the outgroup, then he gets the horn. 

#### Steps to Reproduce
1. Stand on outgroup farm for 30 seconds. 
2. Click 'yes'

#### Additional Context
See video

### Version

0.1.0

### Which aspect(s) of the project is this bug affecting?

game-gameplay

### Screenshots

https://github.com/user-attachments/assets/e9df2e7c-c711-4f8e-a075-3f8c3de39599

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by DangerousVanilla** [comment]
Adding some additional info about this I discovered:

If you wait a bit after disappearing you'll finally see your horn:
![image](https://github.com/user-attachments/assets/2e1455f3-5896-4544-bdb4-1140a3c32e4f)

In this partially invisible state you can put on the glasses and they will appear as if you're there wearing them:
![image](https://github.com/user-attachments/assets/e4e2721f-bd5d-4363-bd5d-ea0c790c0cc4)

If you continue to wait even longer you'll eventually get your body back, however, once this happens your character now appears on top of the glasses:
![image](https://github.com/user-attachments/assets/4a0b56c1-2036-499d-96d4-e4e88074a175)

This persists even after taking them off and putting them back and after moving to a new area.

**Comment by HubertReX** [comment]
Please elaborate more on precise timing of the expected behavior:

`The player should be visible, with a gradually changing appearance: First he loses all his items (hat, necklace), then he gets the same colour as the outgroup, then he gets the horn.`

The current logic in code is as follows:

1. after spending `30 sec` inside Outgroup area, a menu with question about group change is shown
2. if player selects `Yes` he instantly looses the `hat` and the `necklace` 
3. currently the player body is invisible for `2 minutes` - this is clearly to be fixed, new body should be visible instantaneously 
4. after `1 minute` player receives `horn` which is semitransparent at first, but gradually becomes opaque

Should the player loose `hat` and `necklace` gradually (fading to invisible for `1 minute`)?

**Comment by sloukit** [comment]
The logic should be as follows:
1. After spending 30 sec inside outgroup area, a menu with question about group change is shown
2. If player selects yes, he should instantly lose his necklace
3. If the player chooses "yes", they should lose their necklace immediately
4. He will lose the hat after another minute (i.e. one minute after choosing "Yes")
5. He will get the same colour as the (former) outgroup after another minute (i.e. two minutes after choosing "yes")
6. Then, after another minute (i.e. three minutes after choosing "yes"), he gets the horn

The body should be visible at all times.

**Comment by DangerousVanilla** [comment]
Fixed in PR243
